# Generated by Django 5.0.1 on 2024-01-26 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('cp', models.CharField(max_length=5)),
                ('nom_contacto', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_estado', message='El estado no puede contener números.', regex='^[a-zA-Z]+$')])),
            ],
        ),
    ]
