# Generated by Django 5.0.1 on 2024-01-26 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(code='invalid_estado', message='El estado no puede contener números.', regex='^[a-zA-Z]+$')]),
        ),
    ]
