# Generated by Django 5.0.1 on 2024-01-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioAdmin', '0002_alter_cliente_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=600, null=True)),
                ('costo', models.CharField(blank=True, max_length=20, null=True)),
                ('plan', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
