# Generated by Django 5.0.1 on 2024-01-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioAdmin', '0003_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha del ticket')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre del cliente')),
                ('contrato', models.CharField(max_length=80, verbose_name='Contrato')),
                ('periodo', models.CharField(max_length=80, verbose_name='Periodo')),
                ('inicio', models.CharField(max_length=80, verbose_name='Inicio')),
                ('termino', models.CharField(max_length=80, verbose_name='Término')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('servicio', models.CharField(max_length=13, verbose_name='Servicio')),
                ('nom_contacto', models.CharField(max_length=50, verbose_name='Contacto')),
                ('mensaje', models.CharField(max_length=600, verbose_name='Asunto del ticket')),
                ('archivo', models.FileField(upload_to='ticket_archivos/', verbose_name='Archivo')),
            ],
        ),
    ]
