# Generated by Django 5.0.1 on 2024-01-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioAdmin', '0004_soporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('ao', 'All in One'), ('pc', 'Escritorio'), ('lap', 'Laptop')], default='no', max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=10)),
                ('procesador', models.CharField(max_length=50)),
                ('tipo_disco', models.CharField(choices=[('hdd', 'HDD'), ('ssd', 'SSD')], default='no', max_length=3)),
                ('uso_disco', models.CharField(blank=True, max_length=15, null=True)),
                ('ip_local', models.CharField(max_length=15)),
                ('anydesk', models.CharField(max_length=12)),
                ('nom_usuario', models.CharField(max_length=50)),
                ('nom_antivirus', models.CharField(max_length=20)),
                ('vig_antivirus', models.DateField()),
                ('office', models.CharField(max_length=30)),
                ('vig_office', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Soporte',
        ),
    ]
